services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be_app_hpai
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      # - ./:/var/www/html
      - ./storage:/var/www/html/storage
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel
    command: >
      bash -c "
      echo 'Waiting for database...';

      php artisan migrate:fresh;

      if [ ! -f '/var/www/html/storage/passport_installed' ]; then
        php artisan passport:key --force
        php artisan passport:client --personal
        touch /var/www/html/storage/passport_installed;
      fi

      if [ ! -f '/var/www/html/storage/seeds_run' ]; then
        php artisan db:seed;
        touch /var/www/html/storage/seeds_run;
      fi

      exec php-fpm
      "

  db:
    image: postgres:latest
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d laravel"]
      interval: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8012:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:
    driver: local
