services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be_app_hpai
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      # - ./:/var/www
      - ./storage:/var/www/storage
    networks:
      - laravel

  db:
    image: postgres:latest
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8012:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:
    driver: local
